server:
  port: ${PORT:8080}

spring:
  application:
    name: vault
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/vault}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  allow-credentials: true

security:
  jwt:
    secret-base64: ${JWT_SECRET_BASE64:} # 256-bit base64-encoded secret
    issuer: ${JWT_ISSUER:password-notes-vault}
    access-token-ttl-minutes: ${JWT_TTL_MINUTES:120}
    cookie-name: ${JWT_COOKIE_NAME:va_session}
    cookie-domain: ${JWT_COOKIE_DOMAIN:}
    cookie-same-site: ${JWT_COOKIE_SAMESITE:Lax}
    cookie-secure: ${JWT_COOKIE_SECURE:false}

encryption:
  aes:
    key-base64: ${AES_KEY_BASE64:} # 256-bit base64 key (32 bytes)
    iv-bytes: 12
