server:
  port: ${PORT:8080}

spring:
  application:
    name: password-notes-vault
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vault}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "Authorization,Cache-Control,Content-Type"
    allow-credentials: true

app:
  jwt:
    secret: ${JWT_SECRET:change-this-in-prod-32-bytes-minimum-change-this}
    issuer: vault-app
    access-token-ttl-minutes: ${JWT_ACCESS_TTL_MINUTES:60}
  crypto:
    aes-key: ${AES_KEY_BASE64:}
    salt: ${PBKDF2_SALT_BASE64:}
    pbkdf2-iterations: ${PBKDF2_ITERATIONS:120000}

logging:
  level:
    org.springframework.security: INFO
    com.vault: DEBUG

